### ISSUE TITLE
I'm running build on google cloud build, can i use google auth instead of using the JSON file?

### ISSUE THREAD

**Issue by lappazos** [datopian/giftless#108]

**Comment by rufuspollock** [comment]
@lappazos thanks for asking. It would be a good idea but think it may require some work to do that.

**Comment by rra** [comment]
I believe all you need to do is make the credential parameters optional and create the Google cloud storage client with simply `Client()`. Google's libraries will use workload identity by default if you don't provide a credential file, so I think the only thing preventing that right now is that `_load_credentials` requires one of the credential file options to be set.

**Comment by rufuspollock** [comment]
@rra thanks for the tip. Closing as FIXED.

**Comment by rra** [comment]
I don't think this is fixed, unless I'm missing something. `_load_credentials` still requires one of the credential options to be set. I think the last `else` branch of `_load_credentials` needs to be changed to return `None` so that `None` is passed in as credentials, which will use workload identity.

**Comment by rufuspollock** [comment]
@rra thanks for clarifying.

**Comment by athornton** [comment]
Addressed in https://github.com/datopian/giftless/pull/120

**Comment by rufuspollock** [comment]
@athornton with your coder merged does this make this fixed?

**Comment by athornton** [comment]
Yeah, I think so.  A new container build/push would be ideal, but I think if you just check it out and run `docker build` you'll get the changes.

Note that if you're doing this under K8s actually setting up the service account mappings is a lot of pain, but it does work once you have all the right objects bound together.

**Comment by rufuspollock** [comment]
FIXED.
