### ISSUE TITLE
Add support for CGI middleware

### ISSUE THREAD

**Issue by aymanbagabas** [datopian/giftless#117]
Support using Giftless as a CGI module the same way Giftless supports WSGI.

**Comment by vit-zikmund** [comment]
This looks like a matter of [uWSGI configuration](https://uwsgi-docs.readthedocs.io/en/latest/CGI.html) than anything else. Giftless is [actually served](https://github.com/datopian/giftless/blob/a984aa0f34e11b8b186c0b44139b9b7cd79898e1/Dockerfile#L58-L60) via uWSGI, which provides the WSGI interface. Feel free to contribute a working example.

**Comment by rufuspollock** [comment]
FIXED. From @vit-zikmund response my understand is that this is already possible and just requires a config in uWSGI config so i'm going to close.

@athornton @vit-zikmund  lmk if any alternative views on this.
