### ISSUE TITLE
Docker container doesn't die gracefully on SIGTERM

### ISSUE THREAD

**Issue by vit-zikmund** [datopian/giftless#131]
It's because the underlying `uwsgi <2.1` (which is not released yet) "brutally reloads" on SIGTERM instead of gracefully shutting down as any other sane process. I just found this out looking at the live log while updating giftless in our kubernetes cluster. The uwsgi author [acknowledges the situation](https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html) and tells the concerned audience to use SIGINT or SIGQUIT for that matter.
Well, as it's currently impossible to override the "stopsignal" from a kubernetes container configuration, we could easily go ahead and specify the `STOPSIGNAL` directive in the `Dockerfile`. They have also have a commandline switch for that, but that doesn't seem that nice (and then restricts one to do the "brutal reloads" :smile:, which might be a shame, who knows).

**Comment by demenech** [comment]
**FIXED.** See https://github.com/datopian/giftless/commit/7f16de534c25b7bab4040a18c1feabb8257276e2
