### ISSUE TITLE
[docs][question]

### ISSUE THREAD

**Issue by hannelita** [datopian/giftless#14]
If we're trying to set up a local server for test, what's the endpoint we should specify in the .lfsconfig file? "http://127.0.0.1:5000/"?

**Comment by shevron** [comment]
The path of the URL should be of the sort `/myorg/myrepo` where `myorg` is an org / owner name and `myrepo` is a repository name. 

The port depends on how you have Giftless running (and can be configured). See the README on how to run Giftless in HTTP mode in different ways (take care that by default the Docker image will listen for WSGI requests, not HTTP!), and set the port in the URL accordingly.

**Comment by hannelita** [comment]
Thanks @shevron ! Do I also need any sort of authentication when running the server locally?

**Comment by shevron** [comment]
You don't have to have authentication, and currently the only sort of real authentication that is implemented is JWT based which is not really compatible with `git lfs` IIRC (maybe it is but needs to be configured somehow). 

You can configure Giftless to accept unauthenticated requests by setting the following in the config YAML file: 

```yaml
AUTH_PROVIDERS:
  - giftless.auth.allow_anon:read_write
```

**Comment by hannelita** [comment]
@shevron When using the YAML file, I can't get it to accept LocalStorage. Is there any example of a .yaml file for this setting? Thanks

**Comment by shevron** [comment]
> @shevron When using the YAML file, I can't get it to accept LocalStorage. Is there any example of a .yaml file for this setting? Thanks

By default if you specify no transfer adapters in the YAML file, it will use local storage and save to a directory called `lfs-storage` in the CWD (probably project root), as this is what is configured by default in `config.py`.

If you still want to configure something explicitly, I haven't tested it but I think this will work:

```yaml
TRANSFER_ADAPTERS:
  basic:
    factory: giftless.transfer.basic_streaming:factory
    options: 
      storage_class: LocalStorage
      storage_options: 
        path: /path/to/storage`
```
Note that `/path/to/storage` can be relative to the working directory or absolute. It must exist and be writable by the user running Giftless, or if it does not exist it must be *creatable* by the user running Giftless, i.e. the parent directory needs to be writable.

**Comment by hannelita** [comment]
@shevron Thanks! This was my .yaml file:

```shell
AUTH_PROVIDERS:
  - giftless.auth.allow_anon:read_write
```

But it does not seem to work for local storage. 
I had to add the config you suggested. Then it worked, thanks!! 

```shell
TRANSFER_ADAPTERS:
  basic:
    factory: giftless.transfer.basic_streaming:factory
    options: 
      storage_class: LocalStorage
```
(path is set by default on the code)
