### ISSUE TITLE
[enhancement] Use automatic LFS server discovery endpoints

### ISSUE THREAD

**Issue by vit-zikmund** [datopian/giftless#151]
Hello again,

while trying to implement a reverse proxy that hides a regular git(hub) repo and giftless under one hostname for https://github.com/datopian/giftless/issues/128#issuecomment-1887607460, I ran into some unfortunate endpoint rewriting needs that arise from the fact that giftless doesn't follow the [automatic LFS server discovery](https://github.com/git-lfs/git-lfs/blob/main/docs/api/server-discovery.md). I.e. appending `.git/info/lfs` to the usual git repo URL for its endpoints. This gets worse when using the `basic_streaming` transfer adapter, which exposes the objects at `<repopath>/objects/storage`, which needs yet another routing rule which potentially shadows anything on that path in the git repo.

Giftless easily can (and I believe it should) natively play along with this and keep all its endpoints behind the `<repopath>.git/info/lfs/` prefix. This would be much easier and cleaner to route, without really impacting any of the giftless functionality.

As such change would be a breaking one for current users, I believe we could govern this with a config variable like `LEGACY_ENDPOINTS` or so. On the other hand, this would surely bloat the testing code and as giftless hasn't seen a release for quite some time (I suppose most active users build it from `main` anyway), this could be a perfect material before the impending new release is dropped ;) After all, no api stability is to be expected for a tool with version starting with zero :stuck_out_tongue_closed_eyes:

As usual, I have a PR ready :wink:

**Comment by athornton** [comment]
It's got to have a feature flag (disabled by default) and some sort of deprecation warning.  We can't break absolutely everyone who is a current giftless user who doesn't read the release notes carefully.  I've got dozens of repos that would need reconfiguring and hundreds of users who would need to reread our documentation about "How to Use Git-LFS At Rubin", which would have to change.

A notice that that flag will become the default at some point in the future and that the current endpoints will be deprecated would be fine.
