### ISSUE TITLE
Better test coverage for the GCP storage adapter

### ISSUE THREAD

**Issue by hannelita** [datopian/giftless#20]
## Acceptance

- [ ]  Better mocks for GCP; at this time there are only basic unit tests
- [ ] Support for CI / End to end test with cypress (?)

**Comment by shevron** [comment]
Suggestion: write automated, unmocked tests (that actually require access to live GCS bucket). These can be run on demand locally, will be extensive but slow. Then, cover these tests with `pyvcr` / `pytest-vcr` so they can be mocked for faster running / CI tests.
