### ISSUE TITLE
Normalize configuration handling: YAML or ENV variables or both?

### ISSUE THREAD

**Issue by hannelita** [datopian/giftless#22]
At this time we use a YAML file to load specific configs (providers, credentials, etc).
When deploying into a PaaS, it would be good to provide an env-based configuration system.

## Analysis
From the comments: Should we support both a YAML file config and an `.env` config or just one of them? See https://github.com/datopian/giftless/issues/22#issuecomment-669109116

**Comment by rufuspollock** [comment]
I've thought about this and easiest would be to check an env var *and* fallback to local file e.g.

```
GIFTLESS_CONFIG
GIFTLESS_CONFIG_PATH
```

GIFTLESS_CONFIG is a yaml string ... 

We could also allow selective values as env vars ...

**Comment by hannelita** [comment]
Please notice #24 could be better and is just a WIP phase.
This PR DOES NOT remote YAML support. It just adds an .env file as alternative config for PaaS. As a consequence, it will:

- Break the tests if there a `.env` is present (bc it will have priority over the YAML file). Ideally configure dotenv with pytest. (note: Tests are fine if no .env file is present)
- Allow duplicated config (on YAML and on .env). This can be bad for the user.

**Comment by pdelboca** [comment]
@rufuspollock Can we consider this ticket closed by PR #24 ?

**Comment by hannelita** [comment]
@pdelboca @rufuspollock I think it falls back to a design quesiton:
- Do we really want to support both? I don't think it makes sense and I did it as a terrible short-term-under-pressure-solution to support GCP. 
Should we move over `.env` configuration (as a standard way to handle cloud config and middleware config on the same place)? If that is the case, this issue is not resolved.
Instead, if we decide to support both, we can close this issue.

**Comment by shevron** [comment]
I really don't think environment variables (or .env files) capture all the complexity of configuration as required by Giftless, such as nested configuration, and I'd hate us to drop support for YAML files just because of Heroku's limitations (is Heroku really a major production target platform for us?).

I agree that currently configuration handling is not ideal, but I think this needs a more board design discussion and I don't think `.env` or falling back to environment variables only is the ideal solution.

**Comment by shevron** [comment]
BTW: 

> We could also allow selective values as env vars ...

This is already the case. Giftless uses a very simple configuration management library I wrote a few years back called `figcan`. I admit this is very simplistic, but it already allows out of the box overwriting of any config value using a specially crafted env var. I need to better document this, and I think it is somewhat cumbersome, but you could, for example do:

```
export GIFTLESS_TRANSFER_ADAPTERS_basic_options_storage_class = giftless.storage.google_cloud:GoogleCloudBlobStorage
```

To override the following YAML structure:
```yaml
GIFTLESS_TRANSFER_ADAPTERS:
    basic:
        options:
            storage_class: LocalStorage
```

This is not perfect, for once it falls apart when you want to overwrite a config option that is nested in a list and not a dictionary. Also, it is clearly not "pretty". Whether it is uglier or not than providing a YAML / JSON string as an env var and then parsing it is something I can't decide on. 

But for the sake of discussion, I suggest we first discuss:

1. Is this currently a problem that we care about?
2. Is Heroku a platform we want to support in an "elegant" way or could this kind of hack work just as well for it? 
3. Is there some other way to support Heroku and similar platforms without solely relying on environment variables? What do other platforms do if they require some config / secrets files? e.g. pull a file from an S3 bucket? 
4. Are we willing to drop support for YAML files and switch entirely to `.env` if no other suitable solution is found?

**Comment by shevron** [comment]
Also BTW, when thinking about config, it would be good to think about splitting our server config away from the Flask config infrastructure. I'm not sure I want to couple our domain-specific config with Flask. The only exception to this I see may be the `MIDDLEWARE` config option which is to some extent not domain specific but applies to the HTTP stack (and will work with Flask and also any other WSGI based server).

**Comment by hannelita** [comment]
@shevron I agree there are many points we could discuss. My final 2 cents - @rufuspollock suggested we need to focus on GCP integration. I think we can narrow down the scope of this discussion to: "There is a technical debt in the solution I implemented (it is redundant to support the .env in the way I'm doing). Are we going to do something about this right now or leave it as it is?"

**Comment by hannelita** [comment]
3 options
* Leave as it is
* Move into .env
* Leave the YAML config to middleware related configs and .env for storage credentials

**Comment by hannelita** [comment]
@shevron `.env` that I'm using

```bash
TRANSFER_ADAPTERS.basic.factory=giftless.transfer.basic_streaming:factory
TRANSFER_ADAPTERS.basic.options.storage_class=..storage.google_cloud:GoogleCloudBlobStorage
TRANSFER_ADAPTERS.basic.options.storage_options.bucket_name=my-bucket
TRANSFER_ADAPTERS.basic.options.storage_options.api_key=API_KEY
TRANSFER_ADAPTERS.basic.options.storage_options.account_json_path=OPTIONAL PATH
AUTH_PROVIDERS='giftless.auth.allow_anon:read_write'
YAML_CONTENT="TRANSFER_ADAPTERS:
  basic:
    factory: giftless.transfer.basic_streaming:factory
    options:
      storage_class: ..storage.google_cloud:GoogleCloudBlobStorage
      storage_options:
        project_name: datahub-next-test
        bucket_name: datahub-jjj
        api_key: KEY
        account_json: PATH/TO.json
AUTH_PROVIDERS:
  - giftless.auth.allow_anon:read_write
"
GCP_CREDENTIALS='{
... JSON File content
'}
```

**Comment by shevron** [comment]
Suggestion: hybrid approach, YAML file for "base" configuration and support for environment variables to override any config key - but not a single env var that includes all YAML as a string. Env vars will be auto-parsed and can be used to override or set any *non-complex* value. 

This will require an enhancement or replacement of the `figcan` library we currently use for merging configuration. 

Some examples:
```
# As YAML:
TRANSFER_ADAPTERS:
    basic:
        options:
            storage_class: LocalStorage
            storage_options:
                path: /foo
```

```
# as a .env file:
GIFTLESS.TRANSFER_ADAPTERS.BASIC.OPTIONS.STORAGE_CLASS = giftless.storage.google_cloud:GoogleCloudBlobStorage
GIFTLESS.TRANSFER_ADAPTERS_BASIC.OPTIONS.STORAGE_OPTIONS.PATH = /foo
```

Need to specify: 
- How are lists handled? Appending an item to a list or completely replacing a list
- Can we delete object keys? e.g. if the base file defines a `basic` transfer adapter and I want to delete it?
- How are different scalar types handled (str, int, bool, null, float) in values?

**Comment by shevron** [comment]
This is kind of done and documented here: https://giftless.datopian.com/en/latest/configuration.html . 

While configuration handling is not ideal, I don't think it's bad enough to change the behavior at this  point, and I think that between the different options we have covered all our bases. 

I'm closing, if we want to change how config is handled in the future I'd suggest re-opening the discussion.
