### ISSUE TITLE
Google cloud credentials

### ISSUE THREAD

**Issue by hannelita** [datopian/giftless#23]
As a developer trying to deploy Giftless with GCP on Heroku (or any other PaaS), I would like to configure my credential files without having to track them (i.e. as an env var or a group of env vars).

At this time I would need to either put it into the YAML file or specify a path and track the credentials.json file.

**Comment by rufuspollock** [comment]
@hannelita what about our "hack" idea of have env var and then writing them out to a temp file prior to loading google code.

**Comment by hannelita** [comment]
https://googleapis.dev/python/google-cloud-core/latest/_modules/google/cloud/client.html#ClientWithProject

Trying to use an alternative constructor with a different credentials object

**Comment by hannelita** [comment]
#25 fixes this issue
