### ISSUE TITLE
Naming: gitfless / gifted / gifts / gitfs / gitcloud

### ISSUE THREAD

**Issue by rufuspollock** [datopian/giftless#30]
I get that giftless is a bit a better as it fits git + lfs a bit nicer. However, it has a bit of a negative sense. You have now gifts for me 😢 

gifted or gifts still has git + f (or fs) of lfs and is more positive 🎁 

Finally we could go for giftly which has git + lf (but no s).

Options

* giftless
* gifted
* gifts
* gitfs - this could still be pronounced gifts and also has that sense of git + filesystem
* gitcloud - this would keep the purpose

What do people think?

**Comment by shevron** [comment]
I like `giftless` but if I had to change it I would go with `giftd` (a bit like "gifted" but less arrogant and has that familiar "`d` as in daemon" suffix). My 2nd vote would be to `gifts`.

**Comment by shevron** [comment]
To clarify "giftd" is pronounced "gifted".

**Comment by rufuspollock** [comment]
@pwalsh @pdelboca any votes/preferences?

**Comment by hannelita** [comment]
My vote goes for giftless (as it is)

**Comment by rufuspollock** [comment]
FIXED. Staying with giftless.
