### ISSUE TITLE
Better test coverage for the Azure storage adapter

### ISSUE THREAD

**Issue by rufuspollock** [datopian/giftless#32]
* [ ] Better mocks for Azure; at this time there are only basic unit tests
 * [ ] Support for CI / End to end test with cypress (?)

**Comment by shevron** [comment]
I implemented automated tests for the Azure storage class using a live Azure account (if key is provided) or using recorded vcrpy based mocking if no live account is configured. 

Did not look into end-to-end tests for now, we can open a separate issue for this as it is a completely different scope.
