### ISSUE TITLE
[auth] support for ssh-initiated auth?

### ISSUE THREAD

**Issue by ailin-nemui** [datopian/giftless#82]
Hi, the git-lfs client supports a weird ssh-initiated authentication, whereby it will dial to `ssh hostname git-lfs-authenticate group/project.git upload`. Is this something in scope for your server?

**Comment by shevron** [comment]
Currently, I don't think this is in the scope of Giftless, and here's why: the `ssh git-lfs-authenticate` protocol is actually intended for the hostname that runs the Git repository, not the Git LFS hostname. `git-lfs` will [ssh to the hostname on which the repository is hosted](https://github.com/git-lfs/git-lfs/blob/main/docs/api/authentication.md#ssh). This command can return some headers to be sent to the Git LFS server (e.g. Giftless) but it is not up to the GIT LFS server to listen to SSH or to run this command, in my opinion. Typically, people using Giftless will have Giftless on a different hostname than the git repository (although this is not always the case). 

Perhaps, there is a way to hook Giftless or `pyjwt` to an SSH server and respond to the `git-lfs-authenticate` command with an `Authorization` header with a bearer JWT token that will be accepted by Giftless. Perhaps this is doable even right now and we just need to document how to set it up. But I don't think we'll have Giftless running the SSH server itself. 

That said, I'd love to hear more about your need / use case so we can look into this, as I think the authentication / authorization story in Giftless still needs a lot of work.

**Comment by ailin-nemui** [comment]
fair enough, thanks for your response! I was researching how to integrate an LFS server with Git and looking at available implementations; while using GitHub for the regular repo and a third-party server for the large files.

Making it seamless is a bit tricky but since most of us already use ssh to push to GitHub, it might be more natural to (re-)use the SSH key

**Comment by shevron** [comment]
The problem with an SSH based protocol is that without access to the user's private key, Giftless has no way of verifying the user's identity and permissions with Github. Even if Giftless exposes an SSH interface of it's own, deciding how to respond to a `git-lfs-authenticate` command on that SSH interface would be tricky and complex. 

Giftless has a pretty flexible architecture so it allows creating custom auth modules pretty easily, and I can see a module that accepts a username / token / password combination via HTTP Basic and uses that to check the user's identity and permissions against GitHub, for example using OAuth2 and the REST API. But right now this is not implemented, and I don't have enough knowledge to say how difficult it is to implement.

**Comment by shevron** [comment]
Closing this, if there are specific feature requests / tasks they should be reported separately.

**Comment by ailin-nemui** [comment]
(everything you said is right). just fyi in case you ever look again at this feature, the git lfs client will indeed ssh to the host name of the LFS server as set in .lfsconfig! it should be possible to come up with such a script, as outlined by you, that would return such a bearer header.

best,
